# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-30 14:50
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('phone', models.CharField(max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否管理员')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='注册日期')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='余额')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='押金')),
                ('recipient_name', models.CharField(max_length=10, null=True, verbose_name='收货人姓名')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='收货地址')),
                ('recipient_phone', models.CharField(max_length=20, null=True, verbose_name='收货电话')),
                ('zip_code', models.CharField(max_length=6, null=True, verbose_name='收货邮编')),
                ('openid', models.CharField(max_length=50, null=True, verbose_name='用户的唯一标识')),
                ('nickname', models.CharField(max_length=50, null=True, verbose_name='用户的昵称')),
                ('sex', models.CharField(max_length=2, null=True, verbose_name='性别')),
                ('province', models.CharField(max_length=50, null=True, verbose_name='省份')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='城市')),
                ('country', models.CharField(max_length=50, null=True, verbose_name='国家')),
                ('headimgurl', models.CharField(max_length=255, null=True, verbose_name='头像地址')),
                ('subscribe', models.BooleanField(default=True, verbose_name='是否订阅')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
